/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface AturanBebanPerusahaan {
  'aktif' : boolean,
  'createdAt' : bigint,
  'jamMax' : bigint,
  'jamMin' : bigint,
  'nilai' : bigint,
  'polaBeban' : { 'TAMBAH_PER_JAM' : null } |
    { 'TAMBAH_JAM_TETAP' : null },
  'tipePartner' : TipePartner,
}
export interface ClientProfile {
  'name' : string,
  'whatsapp' : string,
  'email' : string,
  'company' : string,
}
export interface InternalProfile {
  'name' : string,
  'role' : InternalRole,
  'whatsapp' : string,
  'email' : string,
}
export type InternalRole = { 'admin' : null } |
  { 'finance' : null } |
  { 'concierge' : null } |
  { 'asistenmu' : null };
export interface KamusPekerjaan {
  'aktif' : boolean,
  'createdAt' : bigint,
  'tipePartnerBoleh' : Array<TipePartner>,
  'kategoriPekerjaan' : string,
  'jenisPekerjaan' : string,
  'jamStandar' : bigint,
}
export interface KonstantaUnitClient {
  'unitKeJamPerusahaan' : bigint,
  'updatedAt' : bigint,
}
export type LayananTypeV4 = { 'EFEKTIF' : null } |
  { 'JAGA' : null } |
  { 'RAPI' : null } |
  { 'FOKUS' : null } |
  { 'TENANG' : null };
export interface LayananV4 {
  'id' : string,
  'unitUsed' : bigint,
  'unitTotal' : bigint,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'tipe' : LayananTypeV4,
  'isArchived' : boolean,
  'isActive' : boolean,
  'sharedWith' : Array<Principal>,
  'clientPrincipal' : Principal,
  'updatedAt' : bigint,
  'updatedBy' : Principal,
  'asistenmuPrincipal' : Principal,
  'hargaPerUnit' : bigint,
}
export type MasterDataKey = string;
export interface PartnerProfile {
  'keahlian' : string,
  'name' : string,
  'whatsapp' : string,
  'email' : string,
  'domisili' : string,
}
export interface SkillVerified {
  'aktif' : boolean,
  'kode' : string,
  'nama' : string,
  'createdAt' : bigint,
  'kategori' : string,
}
export type TipePartner = { 'junior' : null } |
  { 'senior' : null } |
  { 'expert' : null };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserRole = { 'client' : ClientProfile } |
  { 'internal' : InternalProfile } |
  { 'superadmin' : null } |
  { 'partner' : PartnerProfile };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'archiveLayananV4' : ActorMethod<[string], LayananV4>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'claimSuperadmin' : ActorMethod<[], undefined>,
  'createLayananV4' : ActorMethod<
    [
      {
        'unitTotal' : bigint,
        'tipe' : LayananTypeV4,
        'isActive' : [] | [boolean],
        'sharedWith' : Array<Principal>,
        'clientPrincipal' : Principal,
        'asistenmuPrincipal' : Principal,
        'hargaPerUnit' : bigint,
      },
    ],
    LayananV4
  >,
  'editLayananV4' : ActorMethod<
    [
      string,
      {
        'unitTotal' : [] | [bigint],
        'tipe' : [] | [LayananTypeV4],
        'isActive' : [] | [boolean],
        'sharedWith' : [] | [Array<Principal>],
        'clientPrincipal' : [] | [Principal],
        'asistenmuPrincipal' : [] | [Principal],
        'hargaPerUnit' : [] | [bigint],
      },
    ],
    LayananV4
  >,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserRole]>>,
  'getAturanBeban' : ActorMethod<[string], [] | [AturanBebanPerusahaan]>,
  'getCallerUser' : ActorMethod<[], [] | [UserRole]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserRole]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getKamusPekerjaan' : ActorMethod<[string], [] | [KamusPekerjaan]>,
  'getKonstantaUnitClient' : ActorMethod<[], KonstantaUnitClient>,
  'getMasterData' : ActorMethod<[MasterDataKey], string>,
  'getMasterDataMap' : ActorMethod<[], [] | [Array<[string, string]>]>,
  'getMyUserId' : ActorMethod<[], [] | [string]>,
  'getPartnerVerifiedSkills' : ActorMethod<[Principal], Array<string>>,
  'getSkillVerified' : ActorMethod<[string], [] | [SkillVerified]>,
  'getUser' : ActorMethod<[Principal], [] | [UserRole]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserRole]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'kalkulatorAM' : ActorMethod<
    [string, TipePartner, bigint],
    { 'jamKePartner' : bigint, 'unitClient' : bigint, 'jamPerusahaan' : bigint }
  >,
  'listAllLayananV4' : ActorMethod<[boolean], Array<LayananV4>>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listAturanBeban' : ActorMethod<[], Array<AturanBebanPerusahaan>>,
  'listKamusPekerjaan' : ActorMethod<[], Array<KamusPekerjaan>>,
  'listLayananV4ByClient' : ActorMethod<[Principal, boolean], Array<LayananV4>>,
  'listPartnerVerifiedSkills' : ActorMethod<
    [],
    Array<[Principal, Array<string>]>
  >,
  'listSkillVerified' : ActorMethod<[], Array<SkillVerified>>,
  'pushMasterData' : ActorMethod<[MasterDataKey, string], undefined>,
  'registerClient' : ActorMethod<[ClientProfile], undefined>,
  'registerInternal' : ActorMethod<[InternalProfile], undefined>,
  'registerPartner' : ActorMethod<[PartnerProfile], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserRole], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setKonstantaUnitClient' : ActorMethod<[bigint], undefined>,
  'setLayananV4Active' : ActorMethod<[string, boolean], LayananV4>,
  'setPartnerVerifiedSkills' : ActorMethod<
    [Principal, Array<string>],
    undefined
  >,
  'upsertAturanBeban' : ActorMethod<
    [
      [] | [string],
      TipePartner,
      bigint,
      bigint,
      { 'TAMBAH_PER_JAM' : null } |
        { 'TAMBAH_JAM_TETAP' : null },
      bigint,
      boolean,
    ],
    string
  >,
  'upsertKamusPekerjaan' : ActorMethod<
    [[] | [string], string, string, bigint, Array<TipePartner>, boolean],
    string
  >,
  'upsertSkillVerified' : ActorMethod<
    [[] | [string], string, string, boolean],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];