/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ClientProfile {
  'name' : string,
  'whatsapp' : string,
  'email' : string,
  'company' : string,
}
export interface InternalProfile {
  'name' : string,
  'role' : InternalRole,
  'whatsapp' : string,
  'email' : string,
}
export type InternalRole = { 'admin' : null } |
  { 'finance' : null } |
  { 'concierge' : null } |
  { 'asistenmu' : null };
export interface PartnerProfile {
  'keahlian' : string,
  'name' : string,
  'whatsapp' : string,
  'email' : string,
  'domisili' : string,
}
export type UserRole = { 'client' : ClientProfile } |
  { 'internal' : InternalProfile } |
  { 'superadmin' : null } |
  { 'partner' : PartnerProfile };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'claimSuperadmin' : ActorMethod<[], undefined>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserRole]>>,
  'getCallerUser' : ActorMethod<[], [] | [UserRole]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserRole]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getMyUserId' : ActorMethod<[], [] | [string]>,
  'getUser' : ActorMethod<[Principal], [] | [UserRole]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserRole]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerClient' : ActorMethod<[ClientProfile], undefined>,
  'registerInternal' : ActorMethod<[InternalProfile], undefined>,
  'registerPartner' : ActorMethod<[PartnerProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserRole], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];