/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LayananTypeV4 = IDL.Variant({
  'EFEKTIF' : IDL.Null,
  'JAGA' : IDL.Null,
  'RAPI' : IDL.Null,
  'FOKUS' : IDL.Null,
  'TENANG' : IDL.Null,
});
export const LayananV4 = IDL.Record({
  'id' : IDL.Text,
  'unitUsed' : IDL.Nat,
  'unitTotal' : IDL.Nat,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'tipe' : LayananTypeV4,
  'isArchived' : IDL.Bool,
  'isActive' : IDL.Bool,
  'sharedWith' : IDL.Vec(IDL.Principal),
  'clientPrincipal' : IDL.Principal,
  'updatedAt' : IDL.Int,
  'updatedBy' : IDL.Principal,
  'asistenmuPrincipal' : IDL.Principal,
  'hargaPerUnit' : IDL.Nat,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClientProfile = IDL.Record({
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
});
export const InternalRole = IDL.Variant({
  'admin' : IDL.Null,
  'finance' : IDL.Null,
  'concierge' : IDL.Null,
  'asistenmu' : IDL.Null,
});
export const InternalProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : InternalRole,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
});
export const PartnerProfile = IDL.Record({
  'keahlian' : IDL.Text,
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'domisili' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'client' : ClientProfile,
  'internal' : InternalProfile,
  'superadmin' : IDL.Null,
  'partner' : PartnerProfile,
});
export const TipePartner = IDL.Variant({
  'junior' : IDL.Null,
  'senior' : IDL.Null,
  'expert' : IDL.Null,
});
export const AturanBebanPerusahaan = IDL.Record({
  'aktif' : IDL.Bool,
  'createdAt' : IDL.Int,
  'jamMax' : IDL.Nat,
  'jamMin' : IDL.Nat,
  'nilai' : IDL.Nat,
  'polaBeban' : IDL.Variant({
    'TAMBAH_PER_JAM' : IDL.Null,
    'TAMBAH_JAM_TETAP' : IDL.Null,
  }),
  'tipePartner' : TipePartner,
});
export const KamusPekerjaan = IDL.Record({
  'aktif' : IDL.Bool,
  'createdAt' : IDL.Int,
  'tipePartnerBoleh' : IDL.Vec(TipePartner),
  'kategoriPekerjaan' : IDL.Text,
  'jenisPekerjaan' : IDL.Text,
  'jamStandar' : IDL.Nat,
});
export const KonstantaUnitClient = IDL.Record({
  'unitKeJamPerusahaan' : IDL.Nat,
  'updatedAt' : IDL.Int,
});
export const MasterDataKey = IDL.Text;
export const SkillVerified = IDL.Record({
  'aktif' : IDL.Bool,
  'kode' : IDL.Text,
  'nama' : IDL.Text,
  'createdAt' : IDL.Int,
  'kategori' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'archiveLayananV4' : IDL.Func([IDL.Text], [LayananV4], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'claimSuperadmin' : IDL.Func([], [], []),
  'createLayananV4' : IDL.Func(
      [
        IDL.Record({
          'unitTotal' : IDL.Nat,
          'tipe' : LayananTypeV4,
          'isActive' : IDL.Opt(IDL.Bool),
          'sharedWith' : IDL.Vec(IDL.Principal),
          'clientPrincipal' : IDL.Principal,
          'asistenmuPrincipal' : IDL.Principal,
          'hargaPerUnit' : IDL.Nat,
        }),
      ],
      [LayananV4],
      [],
    ),
  'editLayananV4' : IDL.Func(
      [
        IDL.Text,
        IDL.Record({
          'unitTotal' : IDL.Opt(IDL.Nat),
          'tipe' : IDL.Opt(LayananTypeV4),
          'isActive' : IDL.Opt(IDL.Bool),
          'sharedWith' : IDL.Opt(IDL.Vec(IDL.Principal)),
          'clientPrincipal' : IDL.Opt(IDL.Principal),
          'asistenmuPrincipal' : IDL.Opt(IDL.Principal),
          'hargaPerUnit' : IDL.Opt(IDL.Nat),
        }),
      ],
      [LayananV4],
      [],
    ),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserRole))],
      ['query'],
    ),
  'getAturanBeban' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AturanBebanPerusahaan)],
      ['query'],
    ),
  'getCallerUser' : IDL.Func([], [IDL.Opt(UserRole)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserRole)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getKamusPekerjaan' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(KamusPekerjaan)],
      ['query'],
    ),
  'getKonstantaUnitClient' : IDL.Func([], [KonstantaUnitClient], ['query']),
  'getMasterData' : IDL.Func([MasterDataKey], [IDL.Text], ['query']),
  'getMasterDataMap' : IDL.Func(
      [],
      [IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)))],
      ['query'],
    ),
  'getMyUserId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getPartnerVerifiedSkills' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getSkillVerified' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SkillVerified)],
      ['query'],
    ),
  'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(UserRole)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserRole)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'kalkulatorAM' : IDL.Func(
      [IDL.Text, TipePartner, IDL.Nat],
      [
        IDL.Record({
          'jamKePartner' : IDL.Nat,
          'unitClient' : IDL.Nat,
          'jamPerusahaan' : IDL.Nat,
        }),
      ],
      [],
    ),
  'listAllLayananV4' : IDL.Func([IDL.Bool], [IDL.Vec(LayananV4)], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listAturanBeban' : IDL.Func([], [IDL.Vec(AturanBebanPerusahaan)], ['query']),
  'listKamusPekerjaan' : IDL.Func([], [IDL.Vec(KamusPekerjaan)], ['query']),
  'listLayananV4ByClient' : IDL.Func(
      [IDL.Principal, IDL.Bool],
      [IDL.Vec(LayananV4)],
      ['query'],
    ),
  'listPartnerVerifiedSkills' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Text)))],
      ['query'],
    ),
  'listSkillVerified' : IDL.Func([], [IDL.Vec(SkillVerified)], ['query']),
  'pushMasterData' : IDL.Func([MasterDataKey, IDL.Text], [], []),
  'registerClient' : IDL.Func([ClientProfile], [], []),
  'registerInternal' : IDL.Func([InternalProfile], [], []),
  'registerPartner' : IDL.Func([PartnerProfile], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserRole], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setKonstantaUnitClient' : IDL.Func([IDL.Nat], [], []),
  'setLayananV4Active' : IDL.Func([IDL.Text, IDL.Bool], [LayananV4], []),
  'setPartnerVerifiedSkills' : IDL.Func(
      [IDL.Principal, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'upsertAturanBeban' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        TipePartner,
        IDL.Nat,
        IDL.Nat,
        IDL.Variant({
          'TAMBAH_PER_JAM' : IDL.Null,
          'TAMBAH_JAM_TETAP' : IDL.Null,
        }),
        IDL.Nat,
        IDL.Bool,
      ],
      [IDL.Text],
      [],
    ),
  'upsertKamusPekerjaan' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(TipePartner),
        IDL.Bool,
      ],
      [IDL.Text],
      [],
    ),
  'upsertSkillVerified' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LayananTypeV4 = IDL.Variant({
    'EFEKTIF' : IDL.Null,
    'JAGA' : IDL.Null,
    'RAPI' : IDL.Null,
    'FOKUS' : IDL.Null,
    'TENANG' : IDL.Null,
  });
  const LayananV4 = IDL.Record({
    'id' : IDL.Text,
    'unitUsed' : IDL.Nat,
    'unitTotal' : IDL.Nat,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'tipe' : LayananTypeV4,
    'isArchived' : IDL.Bool,
    'isActive' : IDL.Bool,
    'sharedWith' : IDL.Vec(IDL.Principal),
    'clientPrincipal' : IDL.Principal,
    'updatedAt' : IDL.Int,
    'updatedBy' : IDL.Principal,
    'asistenmuPrincipal' : IDL.Principal,
    'hargaPerUnit' : IDL.Nat,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClientProfile = IDL.Record({
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
  });
  const InternalRole = IDL.Variant({
    'admin' : IDL.Null,
    'finance' : IDL.Null,
    'concierge' : IDL.Null,
    'asistenmu' : IDL.Null,
  });
  const InternalProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : InternalRole,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
  });
  const PartnerProfile = IDL.Record({
    'keahlian' : IDL.Text,
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'domisili' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'client' : ClientProfile,
    'internal' : InternalProfile,
    'superadmin' : IDL.Null,
    'partner' : PartnerProfile,
  });
  const TipePartner = IDL.Variant({
    'junior' : IDL.Null,
    'senior' : IDL.Null,
    'expert' : IDL.Null,
  });
  const AturanBebanPerusahaan = IDL.Record({
    'aktif' : IDL.Bool,
    'createdAt' : IDL.Int,
    'jamMax' : IDL.Nat,
    'jamMin' : IDL.Nat,
    'nilai' : IDL.Nat,
    'polaBeban' : IDL.Variant({
      'TAMBAH_PER_JAM' : IDL.Null,
      'TAMBAH_JAM_TETAP' : IDL.Null,
    }),
    'tipePartner' : TipePartner,
  });
  const KamusPekerjaan = IDL.Record({
    'aktif' : IDL.Bool,
    'createdAt' : IDL.Int,
    'tipePartnerBoleh' : IDL.Vec(TipePartner),
    'kategoriPekerjaan' : IDL.Text,
    'jenisPekerjaan' : IDL.Text,
    'jamStandar' : IDL.Nat,
  });
  const KonstantaUnitClient = IDL.Record({
    'unitKeJamPerusahaan' : IDL.Nat,
    'updatedAt' : IDL.Int,
  });
  const MasterDataKey = IDL.Text;
  const SkillVerified = IDL.Record({
    'aktif' : IDL.Bool,
    'kode' : IDL.Text,
    'nama' : IDL.Text,
    'createdAt' : IDL.Int,
    'kategori' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'archiveLayananV4' : IDL.Func([IDL.Text], [LayananV4], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'claimSuperadmin' : IDL.Func([], [], []),
    'createLayananV4' : IDL.Func(
        [
          IDL.Record({
            'unitTotal' : IDL.Nat,
            'tipe' : LayananTypeV4,
            'isActive' : IDL.Opt(IDL.Bool),
            'sharedWith' : IDL.Vec(IDL.Principal),
            'clientPrincipal' : IDL.Principal,
            'asistenmuPrincipal' : IDL.Principal,
            'hargaPerUnit' : IDL.Nat,
          }),
        ],
        [LayananV4],
        [],
      ),
    'editLayananV4' : IDL.Func(
        [
          IDL.Text,
          IDL.Record({
            'unitTotal' : IDL.Opt(IDL.Nat),
            'tipe' : IDL.Opt(LayananTypeV4),
            'isActive' : IDL.Opt(IDL.Bool),
            'sharedWith' : IDL.Opt(IDL.Vec(IDL.Principal)),
            'clientPrincipal' : IDL.Opt(IDL.Principal),
            'asistenmuPrincipal' : IDL.Opt(IDL.Principal),
            'hargaPerUnit' : IDL.Opt(IDL.Nat),
          }),
        ],
        [LayananV4],
        [],
      ),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserRole))],
        ['query'],
      ),
    'getAturanBeban' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AturanBebanPerusahaan)],
        ['query'],
      ),
    'getCallerUser' : IDL.Func([], [IDL.Opt(UserRole)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserRole)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getKamusPekerjaan' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(KamusPekerjaan)],
        ['query'],
      ),
    'getKonstantaUnitClient' : IDL.Func([], [KonstantaUnitClient], ['query']),
    'getMasterData' : IDL.Func([MasterDataKey], [IDL.Text], ['query']),
    'getMasterDataMap' : IDL.Func(
        [],
        [IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)))],
        ['query'],
      ),
    'getMyUserId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getPartnerVerifiedSkills' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getSkillVerified' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SkillVerified)],
        ['query'],
      ),
    'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(UserRole)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserRole)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'kalkulatorAM' : IDL.Func(
        [IDL.Text, TipePartner, IDL.Nat],
        [
          IDL.Record({
            'jamKePartner' : IDL.Nat,
            'unitClient' : IDL.Nat,
            'jamPerusahaan' : IDL.Nat,
          }),
        ],
        [],
      ),
    'listAllLayananV4' : IDL.Func([IDL.Bool], [IDL.Vec(LayananV4)], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listAturanBeban' : IDL.Func(
        [],
        [IDL.Vec(AturanBebanPerusahaan)],
        ['query'],
      ),
    'listKamusPekerjaan' : IDL.Func([], [IDL.Vec(KamusPekerjaan)], ['query']),
    'listLayananV4ByClient' : IDL.Func(
        [IDL.Principal, IDL.Bool],
        [IDL.Vec(LayananV4)],
        ['query'],
      ),
    'listPartnerVerifiedSkills' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Text)))],
        ['query'],
      ),
    'listSkillVerified' : IDL.Func([], [IDL.Vec(SkillVerified)], ['query']),
    'pushMasterData' : IDL.Func([MasterDataKey, IDL.Text], [], []),
    'registerClient' : IDL.Func([ClientProfile], [], []),
    'registerInternal' : IDL.Func([InternalProfile], [], []),
    'registerPartner' : IDL.Func([PartnerProfile], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserRole], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setKonstantaUnitClient' : IDL.Func([IDL.Nat], [], []),
    'setLayananV4Active' : IDL.Func([IDL.Text, IDL.Bool], [LayananV4], []),
    'setPartnerVerifiedSkills' : IDL.Func(
        [IDL.Principal, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'upsertAturanBeban' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          TipePartner,
          IDL.Nat,
          IDL.Nat,
          IDL.Variant({
            'TAMBAH_PER_JAM' : IDL.Null,
            'TAMBAH_JAM_TETAP' : IDL.Null,
          }),
          IDL.Nat,
          IDL.Bool,
        ],
        [IDL.Text],
        [],
      ),
    'upsertKamusPekerjaan' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(TipePartner),
          IDL.Bool,
        ],
        [IDL.Text],
        [],
      ),
    'upsertSkillVerified' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };