/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserRole = {
    __kind__: "client";
    client: ClientProfile;
} | {
    __kind__: "internal";
    internal: InternalProfile;
} | {
    __kind__: "superadmin";
    superadmin: null;
} | {
    __kind__: "partner";
    partner: PartnerProfile;
};
export interface AturanBebanPerusahaan {
    aktif: boolean;
    createdAt: bigint;
    jamMax: bigint;
    jamMin: bigint;
    nilai: bigint;
    polaBeban: Variant_TAMBAH_PER_JAM_TAMBAH_JAM_TETAP;
    tipePartner: TipePartner;
}
export interface KonstantaUnitClient {
    unitKeJamPerusahaan: bigint;
    updatedAt: bigint;
}
export interface InternalProfile {
    name: string;
    role: InternalRole;
    whatsapp: string;
    email: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface LayananV4 {
    id: string;
    unitUsed: bigint;
    unitTotal: bigint;
    createdAt: bigint;
    createdBy: Principal;
    tipe: LayananTypeV4;
    isArchived: boolean;
    isActive: boolean;
    sharedWith: Array<Principal>;
    clientPrincipal: Principal;
    updatedAt: bigint;
    updatedBy: Principal;
    asistenmuPrincipal: Principal;
    hargaPerUnit: bigint;
}
export interface KamusPekerjaan {
    aktif: boolean;
    createdAt: bigint;
    tipePartnerBoleh: Array<TipePartner>;
    kategoriPekerjaan: string;
    jenisPekerjaan: string;
    jamStandar: bigint;
}
export interface SuperadminSummaryV1 {
    partnerLevelJunior: bigint;
    totalTasks: bigint;
    clientsCount: bigint;
    tasksSelesai: bigint;
    partnerLevelSenior: bigint;
    totalGMV: bigint;
    partnersCount: bigint;
    totalLayananV4: bigint;
    layananActive: bigint;
    partnerLevelExpert: bigint;
    tasksActive: bigint;
}
export interface PartnerProfile {
    keahlian: string;
    name: string;
    whatsapp: string;
    email: string;
    domisili: string;
}
export interface ClientProfile {
    name: string;
    whatsapp: string;
    email: string;
    company: string;
}
export interface SkillVerified {
    aktif: boolean;
    kode: string;
    nama: string;
    createdAt: bigint;
    kategori: string;
}
export type MasterDataKey = string;
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum InternalRole {
    admin = "admin",
    finance = "finance",
    concierge = "concierge",
    asistenmu = "asistenmu"
}
export enum LayananTypeV4 {
    EFEKTIF = "EFEKTIF",
    JAGA = "JAGA",
    RAPI = "RAPI",
    FOKUS = "FOKUS",
    TENANG = "TENANG"
}
export enum TipePartner {
    junior = "junior",
    senior = "senior",
    expert = "expert"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_TAMBAH_PER_JAM_TAMBAH_JAM_TETAP {
    TAMBAH_PER_JAM = "TAMBAH_PER_JAM",
    TAMBAH_JAM_TETAP = "TAMBAH_JAM_TETAP"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    archiveLayananV4(layananId: string): Promise<LayananV4>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    claimSuperadmin(): Promise<void>;
    createLayananV4(input: {
        unitTotal: bigint;
        tipe: LayananTypeV4;
        isActive?: boolean;
        sharedWith: Array<Principal>;
        clientPrincipal: Principal;
        asistenmuPrincipal: Principal;
        hargaPerUnit: bigint;
    }): Promise<LayananV4>;
    editLayananV4(layananId: string, patch: {
        unitTotal?: bigint;
        tipe?: LayananTypeV4;
        isActive?: boolean;
        sharedWith?: Array<Principal>;
        clientPrincipal?: Principal;
        asistenmuPrincipal?: Principal;
        hargaPerUnit?: bigint;
    }): Promise<LayananV4>;
    getAllUsers(): Promise<Array<[Principal, UserRole]>>;
    getAturanBeban(kode: string): Promise<AturanBebanPerusahaan | null>;
    getCallerUser(): Promise<UserRole | null>;
    getCallerUserProfile(): Promise<UserRole | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getKamusPekerjaan(kode: string): Promise<KamusPekerjaan | null>;
    getKonstantaUnitClient(): Promise<KonstantaUnitClient>;
    getMasterData(key: MasterDataKey): Promise<string>;
    getMasterDataMap(): Promise<Array<[string, string]> | null>;
    getMyUserId(): Promise<string | null>;
    getPartnerVerifiedSkills(partner: Principal): Promise<Array<string>>;
    getSkillVerified(kode: string): Promise<SkillVerified | null>;
    getSuperadminSummaryV1(): Promise<SuperadminSummaryV1>;
    getUser(callerPrincipal: Principal): Promise<UserRole | null>;
    getUserProfile(user: Principal): Promise<UserRole | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    kalkulatorAM(kodeKamus: string, tipePartner: TipePartner, beban: bigint): Promise<{
        jamKePartner: bigint;
        unitClient: bigint;
        jamPerusahaan: bigint;
    }>;
    listAllLayananV4(includeArchived: boolean): Promise<Array<LayananV4>>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listAturanBeban(): Promise<Array<AturanBebanPerusahaan>>;
    listKamusPekerjaan(): Promise<Array<KamusPekerjaan>>;
    listLayananV4ByClient(clientPrincipal: Principal, includeArchived: boolean): Promise<Array<LayananV4>>;
    listPartnerVerifiedSkills(): Promise<Array<[Principal, Array<string>]>>;
    listSkillVerified(): Promise<Array<SkillVerified>>;
    pushMasterData(key: MasterDataKey, data: string): Promise<void>;
    registerClient(profile: ClientProfile): Promise<void>;
    registerInternal(profile: InternalProfile): Promise<void>;
    registerPartner(profile: PartnerProfile): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(_profile: UserRole): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setKonstantaUnitClient(unitKeJamPerusahaan: bigint): Promise<void>;
    setLayananV4Active(layananId: string, isActive: boolean): Promise<LayananV4>;
    setPartnerVerifiedSkills(partner: Principal, skillCodes: Array<string>): Promise<void>;
    upsertAturanBeban(kodeOpt: string | null, tipePartner: TipePartner, jamMin: bigint, jamMax: bigint, polaBeban: Variant_TAMBAH_PER_JAM_TAMBAH_JAM_TETAP, nilai: bigint, aktif: boolean): Promise<string>;
    upsertKamusPekerjaan(kodeOpt: string | null, kategoriPekerjaan: string, jenisPekerjaan: string, jamStandar: bigint, tipePartnerBoleh: Array<TipePartner>, aktif: boolean): Promise<string>;
    upsertSkillVerified(kodeOpt: string | null, nama: string, kategori: string, aktif: boolean): Promise<string>;
}
import type { ApprovalStatus as _ApprovalStatus, AturanBebanPerusahaan as _AturanBebanPerusahaan, ClientProfile as _ClientProfile, InternalProfile as _InternalProfile, InternalRole as _InternalRole, KamusPekerjaan as _KamusPekerjaan, LayananTypeV4 as _LayananTypeV4, LayananV4 as _LayananV4, PartnerProfile as _PartnerProfile, SkillVerified as _SkillVerified, TipePartner as _TipePartner, UserApprovalInfo as _UserApprovalInfo, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async archiveLayananV4(arg0: string): Promise<LayananV4> {
        if (this.processError) {
            try {
                const result = await this.actor.archiveLayananV4(arg0);
                return from_candid_LayananV4_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.archiveLayananV4(arg0);
            return from_candid_LayananV4_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimSuperadmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.claimSuperadmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimSuperadmin();
            return result;
        }
    }
    async createLayananV4(arg0: {
        unitTotal: bigint;
        tipe: LayananTypeV4;
        isActive?: boolean;
        sharedWith: Array<Principal>;
        clientPrincipal: Principal;
        asistenmuPrincipal: Principal;
        hargaPerUnit: bigint;
    }): Promise<LayananV4> {
        if (this.processError) {
            try {
                const result = await this.actor.createLayananV4(to_candid_record_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_LayananV4_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLayananV4(to_candid_record_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_LayananV4_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async editLayananV4(arg0: string, arg1: {
        unitTotal?: bigint;
        tipe?: LayananTypeV4;
        isActive?: boolean;
        sharedWith?: Array<Principal>;
        clientPrincipal?: Principal;
        asistenmuPrincipal?: Principal;
        hargaPerUnit?: bigint;
    }): Promise<LayananV4> {
        if (this.processError) {
            try {
                const result = await this.actor.editLayananV4(arg0, to_candid_record_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_LayananV4_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editLayananV4(arg0, to_candid_record_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_LayananV4_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<[Principal, UserRole]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAturanBeban(arg0: string): Promise<AturanBebanPerusahaan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAturanBeban(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAturanBeban(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUser(): Promise<UserRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUser();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUser();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKamusPekerjaan(arg0: string): Promise<KamusPekerjaan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getKamusPekerjaan(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKamusPekerjaan(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKonstantaUnitClient(): Promise<KonstantaUnitClient> {
        if (this.processError) {
            try {
                const result = await this.actor.getKonstantaUnitClient();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKonstantaUnitClient();
            return result;
        }
    }
    async getMasterData(arg0: MasterDataKey): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMasterData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMasterData(arg0);
            return result;
        }
    }
    async getMasterDataMap(): Promise<Array<[string, string]> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMasterDataMap();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMasterDataMap();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyUserId(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyUserId();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyUserId();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartnerVerifiedSkills(arg0: Principal): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerVerifiedSkills(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerVerifiedSkills(arg0);
            return result;
        }
    }
    async getSkillVerified(arg0: string): Promise<SkillVerified | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSkillVerified(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSkillVerified(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSuperadminSummaryV1(): Promise<SuperadminSummaryV1> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuperadminSummaryV1();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuperadminSummaryV1();
            return result;
        }
    }
    async getUser(arg0: Principal): Promise<UserRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async kalkulatorAM(arg0: string, arg1: TipePartner, arg2: bigint): Promise<{
        jamKePartner: bigint;
        unitClient: bigint;
        jamPerusahaan: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.kalkulatorAM(arg0, to_candid_TipePartner_n35(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.kalkulatorAM(arg0, to_candid_TipePartner_n35(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async listAllLayananV4(arg0: boolean): Promise<Array<LayananV4>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllLayananV4(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllLayananV4(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAturanBeban(): Promise<Array<AturanBebanPerusahaan>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAturanBeban();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAturanBeban();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async listKamusPekerjaan(): Promise<Array<KamusPekerjaan>> {
        if (this.processError) {
            try {
                const result = await this.actor.listKamusPekerjaan();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listKamusPekerjaan();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async listLayananV4ByClient(arg0: Principal, arg1: boolean): Promise<Array<LayananV4>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLayananV4ByClient(arg0, arg1);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLayananV4ByClient(arg0, arg1);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPartnerVerifiedSkills(): Promise<Array<[Principal, Array<string>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPartnerVerifiedSkills();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPartnerVerifiedSkills();
            return result;
        }
    }
    async listSkillVerified(): Promise<Array<SkillVerified>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSkillVerified();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSkillVerified();
            return result;
        }
    }
    async pushMasterData(arg0: MasterDataKey, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pushMasterData(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pushMasterData(arg0, arg1);
            return result;
        }
    }
    async registerClient(arg0: ClientProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerClient(arg0);
            return result;
        }
    }
    async registerInternal(arg0: InternalProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerInternal(to_candid_InternalProfile_n45(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerInternal(to_candid_InternalProfile_n45(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async registerPartner(arg0: PartnerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerPartner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerPartner(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserRole_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserRole_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n51(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n51(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setKonstantaUnitClient(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setKonstantaUnitClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setKonstantaUnitClient(arg0);
            return result;
        }
    }
    async setLayananV4Active(arg0: string, arg1: boolean): Promise<LayananV4> {
        if (this.processError) {
            try {
                const result = await this.actor.setLayananV4Active(arg0, arg1);
                return from_candid_LayananV4_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLayananV4Active(arg0, arg1);
            return from_candid_LayananV4_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async setPartnerVerifiedSkills(arg0: Principal, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPartnerVerifiedSkills(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPartnerVerifiedSkills(arg0, arg1);
            return result;
        }
    }
    async upsertAturanBeban(arg0: string | null, arg1: TipePartner, arg2: bigint, arg3: bigint, arg4: Variant_TAMBAH_PER_JAM_TAMBAH_JAM_TETAP, arg5: bigint, arg6: boolean): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertAturanBeban(to_candid_opt_n53(this._uploadFile, this._downloadFile, arg0), to_candid_TipePartner_n35(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_variant_n54(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertAturanBeban(to_candid_opt_n53(this._uploadFile, this._downloadFile, arg0), to_candid_TipePartner_n35(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_variant_n54(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
    async upsertKamusPekerjaan(arg0: string | null, arg1: string, arg2: string, arg3: bigint, arg4: Array<TipePartner>, arg5: boolean): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertKamusPekerjaan(to_candid_opt_n53(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, to_candid_vec_n55(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertKamusPekerjaan(to_candid_opt_n53(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, to_candid_vec_n55(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async upsertSkillVerified(arg0: string | null, arg1: string, arg2: string, arg3: boolean): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertSkillVerified(to_candid_opt_n53(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertSkillVerified(to_candid_opt_n53(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_AturanBebanPerusahaan_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AturanBebanPerusahaan): AturanBebanPerusahaan {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_InternalProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InternalProfile): InternalProfile {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_InternalRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InternalRole): InternalRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_KamusPekerjaan_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KamusPekerjaan): KamusPekerjaan {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_LayananTypeV4_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LayananTypeV4): LayananTypeV4 {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_LayananV4_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LayananV4): LayananV4 {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_TipePartner_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TipePartner): TipePartner {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AturanBebanPerusahaan]): AturanBebanPerusahaan | null {
    return value.length === 0 ? null : from_candid_AturanBebanPerusahaan_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserRole]): UserRole | null {
    return value.length === 0 ? null : from_candid_UserRole_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_KamusPekerjaan]): KamusPekerjaan | null {
    return value.length === 0 ? null : from_candid_KamusPekerjaan_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<[string, string]>]): Array<[string, string]> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SkillVerified]): SkillVerified | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _InternalRole;
    whatsapp: string;
    email: string;
}): {
    name: string;
    role: InternalRole;
    whatsapp: string;
    email: string;
} {
    return {
        name: value.name,
        role: from_candid_InternalRole_n17(_uploadFile, _downloadFile, value.role),
        whatsapp: value.whatsapp,
        email: value.email
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    unitUsed: bigint;
    unitTotal: bigint;
    createdAt: bigint;
    createdBy: Principal;
    tipe: _LayananTypeV4;
    isArchived: boolean;
    isActive: boolean;
    sharedWith: Array<Principal>;
    clientPrincipal: Principal;
    updatedAt: bigint;
    updatedBy: Principal;
    asistenmuPrincipal: Principal;
    hargaPerUnit: bigint;
}): {
    id: string;
    unitUsed: bigint;
    unitTotal: bigint;
    createdAt: bigint;
    createdBy: Principal;
    tipe: LayananTypeV4;
    isArchived: boolean;
    isActive: boolean;
    sharedWith: Array<Principal>;
    clientPrincipal: Principal;
    updatedAt: bigint;
    updatedBy: Principal;
    asistenmuPrincipal: Principal;
    hargaPerUnit: bigint;
} {
    return {
        id: value.id,
        unitUsed: value.unitUsed,
        unitTotal: value.unitTotal,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        tipe: from_candid_LayananTypeV4_n3(_uploadFile, _downloadFile, value.tipe),
        isArchived: value.isArchived,
        isActive: value.isActive,
        sharedWith: value.sharedWith,
        clientPrincipal: value.clientPrincipal,
        updatedAt: value.updatedAt,
        updatedBy: value.updatedBy,
        asistenmuPrincipal: value.asistenmuPrincipal,
        hargaPerUnit: value.hargaPerUnit
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aktif: boolean;
    createdAt: bigint;
    jamMax: bigint;
    jamMin: bigint;
    nilai: bigint;
    polaBeban: {
        TAMBAH_PER_JAM: null;
    } | {
        TAMBAH_JAM_TETAP: null;
    };
    tipePartner: _TipePartner;
}): {
    aktif: boolean;
    createdAt: bigint;
    jamMax: bigint;
    jamMin: bigint;
    nilai: bigint;
    polaBeban: Variant_TAMBAH_PER_JAM_TAMBAH_JAM_TETAP;
    tipePartner: TipePartner;
} {
    return {
        aktif: value.aktif,
        createdAt: value.createdAt,
        jamMax: value.jamMax,
        jamMin: value.jamMin,
        nilai: value.nilai,
        polaBeban: from_candid_variant_n22(_uploadFile, _downloadFile, value.polaBeban),
        tipePartner: from_candid_TipePartner_n23(_uploadFile, _downloadFile, value.tipePartner)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aktif: boolean;
    createdAt: bigint;
    tipePartnerBoleh: Array<_TipePartner>;
    kategoriPekerjaan: string;
    jenisPekerjaan: string;
    jamStandar: bigint;
}): {
    aktif: boolean;
    createdAt: bigint;
    tipePartnerBoleh: Array<TipePartner>;
    kategoriPekerjaan: string;
    jenisPekerjaan: string;
    jamStandar: bigint;
} {
    return {
        aktif: value.aktif,
        createdAt: value.createdAt,
        tipePartnerBoleh: from_candid_vec_n31(_uploadFile, _downloadFile, value.tipePartnerBoleh),
        kategoriPekerjaan: value.kategoriPekerjaan,
        jenisPekerjaan: value.jenisPekerjaan,
        jamStandar: value.jamStandar
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n41(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_tuple_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserRole]): [Principal, UserRole] {
    return [
        value[0],
        from_candid_UserRole_n13(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    client: _ClientProfile;
} | {
    internal: _InternalProfile;
} | {
    superadmin: null;
} | {
    partner: _PartnerProfile;
}): {
    __kind__: "client";
    client: ClientProfile;
} | {
    __kind__: "internal";
    internal: InternalProfile;
} | {
    __kind__: "superadmin";
    superadmin: null;
} | {
    __kind__: "partner";
    partner: PartnerProfile;
} {
    return "client" in value ? {
        __kind__: "client",
        client: value.client
    } : "internal" in value ? {
        __kind__: "internal",
        internal: from_candid_InternalProfile_n15(_uploadFile, _downloadFile, value.internal)
    } : "superadmin" in value ? {
        __kind__: "superadmin",
        superadmin: value.superadmin
    } : "partner" in value ? {
        __kind__: "partner",
        partner: value.partner
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    finance: null;
} | {
    concierge: null;
} | {
    asistenmu: null;
}): InternalRole {
    return "admin" in value ? InternalRole.admin : "finance" in value ? InternalRole.finance : "concierge" in value ? InternalRole.concierge : "asistenmu" in value ? InternalRole.asistenmu : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    TAMBAH_PER_JAM: null;
} | {
    TAMBAH_JAM_TETAP: null;
}): Variant_TAMBAH_PER_JAM_TAMBAH_JAM_TETAP {
    return "TAMBAH_PER_JAM" in value ? Variant_TAMBAH_PER_JAM_TAMBAH_JAM_TETAP.TAMBAH_PER_JAM : "TAMBAH_JAM_TETAP" in value ? Variant_TAMBAH_PER_JAM_TAMBAH_JAM_TETAP.TAMBAH_JAM_TETAP : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    junior: null;
} | {
    senior: null;
} | {
    expert: null;
}): TipePartner {
    return "junior" in value ? TipePartner.junior : "senior" in value ? TipePartner.senior : "expert" in value ? TipePartner.expert : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    EFEKTIF: null;
} | {
    JAGA: null;
} | {
    RAPI: null;
} | {
    FOKUS: null;
} | {
    TENANG: null;
}): LayananTypeV4 {
    return "EFEKTIF" in value ? LayananTypeV4.EFEKTIF : "JAGA" in value ? LayananTypeV4.JAGA : "RAPI" in value ? LayananTypeV4.RAPI : "FOKUS" in value ? LayananTypeV4.FOKUS : "TENANG" in value ? LayananTypeV4.TENANG : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserRole]>): Array<[Principal, UserRole]> {
    return value.map((x)=>from_candid_tuple_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TipePartner>): Array<TipePartner> {
    return value.map((x)=>from_candid_TipePartner_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LayananV4>): Array<LayananV4> {
    return value.map((x)=>from_candid_LayananV4_n1(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AturanBebanPerusahaan>): Array<AturanBebanPerusahaan> {
    return value.map((x)=>from_candid_AturanBebanPerusahaan_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_KamusPekerjaan>): Array<KamusPekerjaan> {
    return value.map((x)=>from_candid_KamusPekerjaan_n29(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function to_candid_InternalProfile_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InternalProfile): _InternalProfile {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_InternalRole_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InternalRole): _InternalRole {
    return to_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function to_candid_LayananTypeV4_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LayananTypeV4): _LayananTypeV4 {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_TipePartner_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TipePartner): _TipePartner {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unitTotal?: bigint;
    tipe?: LayananTypeV4;
    isActive?: boolean;
    sharedWith?: Array<Principal>;
    clientPrincipal?: Principal;
    asistenmuPrincipal?: Principal;
    hargaPerUnit?: bigint;
}): {
    unitTotal: [] | [bigint];
    tipe: [] | [_LayananTypeV4];
    isActive: [] | [boolean];
    sharedWith: [] | [Array<Principal>];
    clientPrincipal: [] | [Principal];
    asistenmuPrincipal: [] | [Principal];
    hargaPerUnit: [] | [bigint];
} {
    return {
        unitTotal: value.unitTotal ? candid_some(value.unitTotal) : candid_none(),
        tipe: value.tipe ? candid_some(to_candid_LayananTypeV4_n8(_uploadFile, _downloadFile, value.tipe)) : candid_none(),
        isActive: value.isActive ? candid_some(value.isActive) : candid_none(),
        sharedWith: value.sharedWith ? candid_some(value.sharedWith) : candid_none(),
        clientPrincipal: value.clientPrincipal ? candid_some(value.clientPrincipal) : candid_none(),
        asistenmuPrincipal: value.asistenmuPrincipal ? candid_some(value.asistenmuPrincipal) : candid_none(),
        hargaPerUnit: value.hargaPerUnit ? candid_some(value.hargaPerUnit) : candid_none()
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: InternalRole;
    whatsapp: string;
    email: string;
}): {
    name: string;
    role: _InternalRole;
    whatsapp: string;
    email: string;
} {
    return {
        name: value.name,
        role: to_candid_InternalRole_n47(_uploadFile, _downloadFile, value.role),
        whatsapp: value.whatsapp,
        email: value.email
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unitTotal: bigint;
    tipe: LayananTypeV4;
    isActive?: boolean;
    sharedWith: Array<Principal>;
    clientPrincipal: Principal;
    asistenmuPrincipal: Principal;
    hargaPerUnit: bigint;
}): {
    unitTotal: bigint;
    tipe: _LayananTypeV4;
    isActive: [] | [boolean];
    sharedWith: Array<Principal>;
    clientPrincipal: Principal;
    asistenmuPrincipal: Principal;
    hargaPerUnit: bigint;
} {
    return {
        unitTotal: value.unitTotal,
        tipe: to_candid_LayananTypeV4_n8(_uploadFile, _downloadFile, value.tipe),
        isActive: value.isActive ? candid_some(value.isActive) : candid_none(),
        sharedWith: value.sharedWith,
        clientPrincipal: value.clientPrincipal,
        asistenmuPrincipal: value.asistenmuPrincipal,
        hargaPerUnit: value.hargaPerUnit
    };
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TipePartner): {
    junior: null;
} | {
    senior: null;
} | {
    expert: null;
} {
    return value == TipePartner.junior ? {
        junior: null
    } : value == TipePartner.senior ? {
        senior: null
    } : value == TipePartner.expert ? {
        expert: null
    } : value;
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InternalRole): {
    admin: null;
} | {
    finance: null;
} | {
    concierge: null;
} | {
    asistenmu: null;
} {
    return value == InternalRole.admin ? {
        admin: null
    } : value == InternalRole.finance ? {
        finance: null
    } : value == InternalRole.concierge ? {
        concierge: null
    } : value == InternalRole.asistenmu ? {
        asistenmu: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "client";
    client: ClientProfile;
} | {
    __kind__: "internal";
    internal: InternalProfile;
} | {
    __kind__: "superadmin";
    superadmin: null;
} | {
    __kind__: "partner";
    partner: PartnerProfile;
}): {
    client: _ClientProfile;
} | {
    internal: _InternalProfile;
} | {
    superadmin: null;
} | {
    partner: _PartnerProfile;
} {
    return value.__kind__ === "client" ? {
        client: value.client
    } : value.__kind__ === "internal" ? {
        internal: to_candid_InternalProfile_n45(_uploadFile, _downloadFile, value.internal)
    } : value.__kind__ === "superadmin" ? {
        superadmin: value.superadmin
    } : value.__kind__ === "partner" ? {
        partner: value.partner
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_TAMBAH_PER_JAM_TAMBAH_JAM_TETAP): {
    TAMBAH_PER_JAM: null;
} | {
    TAMBAH_JAM_TETAP: null;
} {
    return value == Variant_TAMBAH_PER_JAM_TAMBAH_JAM_TETAP.TAMBAH_PER_JAM ? {
        TAMBAH_PER_JAM: null
    } : value == Variant_TAMBAH_PER_JAM_TAMBAH_JAM_TETAP.TAMBAH_JAM_TETAP ? {
        TAMBAH_JAM_TETAP: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LayananTypeV4): {
    EFEKTIF: null;
} | {
    JAGA: null;
} | {
    RAPI: null;
} | {
    FOKUS: null;
} | {
    TENANG: null;
} {
    return value == LayananTypeV4.EFEKTIF ? {
        EFEKTIF: null
    } : value == LayananTypeV4.JAGA ? {
        JAGA: null
    } : value == LayananTypeV4.RAPI ? {
        RAPI: null
    } : value == LayananTypeV4.FOKUS ? {
        FOKUS: null
    } : value == LayananTypeV4.TENANG ? {
        TENANG: null
    } : value;
}
function to_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TipePartner>): Array<_TipePartner> {
    return value.map((x)=>to_candid_TipePartner_n35(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
